export const ADD_ELEM = "ADD_ELEM"
export const ADD_HISTORY = "ADD_HISTORY"
export const EQUAL = "EQUAL"
export const CLEAR_HISTORY = "CLEAR_HISTORY"
export const CLEAR = "CLEAR"
export const DELETE = "DELETE"
export const THEME= "THEME"
export const ADAPTIVE_HISTORY = "ADAPTIVE_HISTORY"
