describe('Display', () => {

  it('should have a value when button click',  () => {
    cy.visit('/')
    cy.get('button').contains('C').click()
    cy.get('button').contains('5').click()
    cy.get('[data-cy=display-value]').contains('5')
    cy.get('button').contains('+').click()
    cy.get('[data-cy=display-value]').contains('5 + ')
    cy.get('button').contains('4').click()
    cy.get('[data-cy=display-value]').contains('5 + 4')
    cy.get('button').contains('-').click()
    cy.get('[data-cy=display-value]').contains('5 + 4 - ')
    cy.get('button').contains('(').click()
    cy.get('[data-cy=display-value]').contains('5 + 4 - ( ')
    cy.get('button').contains('1').click()
    cy.get('[data-cy=display-value]').contains('5 + 4 - ( 1')
    cy.get('button').contains('*').click()
    cy.get('[data-cy=display-value]').contains('5 + 4 - ( 1 * ')
    cy.get('button').contains('2').click()
    cy.get('[data-cy=display-value]').contains('5 + 4 - ( 1 * 2')
    cy.get('button').contains(')').click()
    cy.get('[data-cy=display-value]').contains('5 + 4 - ( 1 * 2 )')
    cy.get('button').contains('%').click()
    cy.get('[data-cy=display-value]').contains('5 + 4 - ( 1 * 2 ) % ')
    cy.get('button').contains('3').click()
    cy.get('[data-cy=display-value]').contains('5 + 4 - ( 1 * 2 ) % 3')
    cy.get('button').contains('/').click()
    cy.get('[data-cy=display-value]').contains('5 + 4 - ( 1 * 2 ) % 3 / ')
    cy.get('button').contains('6').click()
    cy.get('button').contains('0').click()
    cy.get('button').contains('9').click()
    cy.get('[data-cy=display-value]').contains('5 + 4 - ( 1 * 2 ) % 3 / 609')
    cy.get('button').contains('+').click()
    cy.get('button').contains('7').click()
    cy.get('button').contains('.').click()
    cy.get('button').contains('8').click()
    cy.get('[data-cy=display-value]').contains('5 + 4 - ( 1 * 2 ) % 3 / 609 + 7.8')
    cy.get('button').contains('=').click()
    cy.get('[data-cy=display-value]').contains('16.797')
  })

})

describe('Validation display input', () => {

  it('should have a value when button click',  () => {
    cy.visit('/')
    cy.get('button').contains('C').click()
    cy.get('button').contains('5').click()
    cy.get('[data-cy=display-value]').contains('5')
    cy.get('button').contains('+').click()
    cy.get('[data-cy=display-value]').contains('5 + ')
    cy.get('button').contains('4').click()
    cy.get('[data-cy=display-value]').contains('5 + 4')
    cy.get('button').contains('-').click()
    cy.get('[data-cy=display-value]').contains('5 + 4 - ')
    cy.get('button').contains('(').click()
    cy.get('[data-cy=display-value]').contains('5 + 4 - ( ')
    cy.get('button').contains('1').click()
    cy.get('[data-cy=display-value]').contains('5 + 4 - ( 1')
    cy.get('button').contains('*').click()
    cy.get('[data-cy=display-value]').contains('5 + 4 - ( 1 * ')
    cy.get('button').contains('2').click()
    cy.get('[data-cy=display-value]').contains('5 + 4 - ( 1 * 2')
    cy.get('button').contains(')').click()
    cy.get('[data-cy=display-value]').contains('5 + 4 - ( 1 * 2 )')
    cy.get('button').contains('%').click()
    cy.get('[data-cy=display-value]').contains('5 + 4 - ( 1 * 2 ) % ')
    cy.get('button').contains('3').click()
    cy.get('[data-cy=display-value]').contains('5 + 4 - ( 1 * 2 ) % 3')
    cy.get('button').contains('/').click()
    cy.get('[data-cy=display-value]').contains('5 + 4 - ( 1 * 2 ) % 3 / ')
    cy.get('button').contains('6').click()
    cy.get('button').contains('0').click()
    cy.get('button').contains('9').click()
    cy.get('[data-cy=display-value]').contains('5 + 4 - ( 1 * 2 ) % 3 / 609')
    cy.get('button').contains('+').click()
    cy.get('button').contains('7').click()
    cy.get('button').contains('.').click()
    cy.get('button').contains('8').click()
    cy.get('[data-cy=display-value]').contains('5 + 4 - ( 1 * 2 ) % 3 / 609 + 7.8')
    cy.get('button').contains('=').click()
    cy.get('[data-cy=display-value]').contains('16.797')
  })

})
