describe('Calculator operations', () => {

  it('plus operation',  () => {
    cy.visit('/')
    cy.get('button').contains('5').click()
    cy.get('button').contains('+').click()
    cy.get('button').contains('5').click()
    cy.get('button').contains('=').click()
    cy.get('[data-cy=display-value]').contains('10')

    cy.get('button').contains('C').click()

    cy.get('button').contains('6').click()
    cy.get('button').contains('+').click()
    cy.get('button').contains('0').click()
    cy.get('button').contains('=').click()
    cy.get('[data-cy=display-value]').contains('6')

    cy.get('button').contains('C').click()

    cy.get('button').contains('0').click()
    cy.get('button').contains('+').click()
    cy.get('button').contains('0').click()
    cy.get('button').contains('=').click()
    cy.get('[data-cy=display-value]').contains('0')

    cy.get('button').contains('C').click()

    cy.get('button').contains('5').click()
    cy.get('button').contains('5').click()
    cy.get('button').contains('6').click()
    cy.get('button').contains('7').click()
    cy.get('button').contains('9').click()
    cy.get('button').contains('+').click()
    cy.get('button').contains('1').click()
    cy.get('button').contains('2').click()
    cy.get('button').contains('3').click()
    cy.get('button').contains('8').click()
    cy.get('button').contains('.').click()
    cy.get('button').contains('2').click()
    cy.get('button').contains('6').click()
    cy.get('button').contains('7').click()
    cy.get('button').contains('=').click()
    cy.get('[data-cy=display-value]').contains('56917.267')

    cy.get('button').contains('C').click()

    cy.get('button').contains('3').click()
    cy.get('button').contains('.').click()
    cy.get('button').contains('1').click()
    cy.get('button').contains('2').click()
    cy.get('button').contains('3').click()
    cy.get('button').contains('4').click()
    cy.get('button').contains('5').click()
    cy.get('button').contains('6').click()
    cy.get('button').contains('7').click()
    cy.get('button').contains('8').click()
    cy.get('button').contains('+').click()
    cy.get('button').contains('9').click()
    cy.get('button').contains('.').click()
    cy.get('button').contains('1').click()
    cy.get('button').contains('2').click()
    cy.get('button').contains('3').click()
    cy.get('button').contains('4').click()
    cy.get('button').contains('5').click()
    cy.get('button').contains('6').click()
    cy.get('button').contains('7').click()
    cy.get('button').contains('8').click()
    cy.get('button').contains('=').click()
    cy.get('[data-cy=display-value]').contains('12.247')
  })

  it('minus operation',  () => {

    cy.get('button').contains('C').click()

    cy.get('button').contains('1').click()
    cy.get('button').contains('-').click()
    cy.get('button').contains('9').click()
    cy.get('button').contains('=').click()
    cy.get('[data-cy=display-value]').contains('-8')

    cy.get('button').contains('C').click()

    cy.get('button').contains('7').click()
    cy.get('button').contains('5').click()
    cy.get('button').contains('-').click()
    cy.get('button').contains('0').click()
    cy.get('button').contains('=').click()
    cy.get('[data-cy=display-value]').contains('75')

    cy.get('button').contains('C').click()

    cy.get('button').contains('6').click()
    cy.get('button').contains('0').click()
    cy.get('button').contains('8').click()
    cy.get('button').contains('-').click()
    cy.get('button').contains('3').click()
    cy.get('button').contains('4').click()
    cy.get('button').contains('6').click()
    cy.get('button').contains('=').click()
    cy.get('[data-cy=display-value]').contains('262')

    cy.get('button').contains('C').click()

    cy.get('button').contains('1').click()
    cy.get('button').contains('6').click()
    cy.get('button').contains('7').click()
    cy.get('button').contains('6').click()
    cy.get('button').contains('.').click()
    cy.get('button').contains('2').click()
    cy.get('button').contains('9').click()
    cy.get('button').contains('3').click()
    cy.get('button').contains('6').click()
    cy.get('button').contains('-').click()
    cy.get('button').contains('2').click()
    cy.get('button').contains('.').click()
    cy.get('button').contains('1').click()
    cy.get('button').contains('1').click()
    cy.get('button').contains('3').click()
    cy.get('button').contains('=').click()
    cy.get('[data-cy=display-value]').contains('1674.181')

    cy.get('button').contains('C').click()
    cy.get('button').contains('-').click()
    cy.get('button').contains('0').click()
    cy.get('button').contains('.').click()
    cy.get('button').contains('2').click()
    cy.get('button').contains('3').click()
    cy.get('button').contains('4').click()
    cy.get('button').contains('-').click()
    cy.get('button').contains('3').click()
    cy.get('button').contains('7').click()
    cy.get('button').contains('8').click()
    cy.get('button').contains('=').click()
    cy.get('[data-cy=display-value]').contains('-378.234')
  })

  it('multiply operation',  () => {
    cy.get('button').contains('C').click()

    cy.get('button').contains('2').click()
    cy.get('button').contains('*').click()
    cy.get('button').contains('2').click()
    cy.get('button').contains('=').click()
    cy.get('[data-cy=display-value]').contains('4')

    cy.get('button').contains('C').click()

    cy.get('button').contains('5').click()
    cy.get('button').contains('3').click()
    cy.get('button').contains('*').click()
    cy.get('button').contains('0').click()
    cy.get('button').contains('=').click()
    cy.get('[data-cy=display-value]').contains('0')

    cy.get('button').contains('C').click()

    cy.get('button').contains('0').click()
    cy.get('button').contains('*').click()
    cy.get('button').contains('0').click()
    cy.get('button').contains('=').click()
    cy.get('[data-cy=display-value]').contains('0')

    cy.get('button').contains('C').click()

    cy.get('button').contains('9').click()
    cy.get('button').contains('6').click()
    cy.get('button').contains('3').click()
    cy.get('button').contains('*').click()
    cy.get('button').contains('0').click()
    cy.get('button').contains('.').click()
    cy.get('button').contains('6').click()
    cy.get('button').contains('=').click()
    cy.get('[data-cy=display-value]').contains('577.8')

    cy.get('button').contains('C').click()

    cy.get('button').contains('3').click()
    cy.get('button').contains('3').click()
    cy.get('button').contains('3').click()
    cy.get('button').contains('6').click()
    cy.get('button').contains('.').click()
    cy.get('button').contains('1').click()
    cy.get('button').contains('9').click()
    cy.get('button').contains('6').click()
    cy.get('button').contains('4').click()
    cy.get('button').contains('*').click()
    cy.get('button').contains('2').click()
    cy.get('button').contains('6').click()
    cy.get('button').contains('.').click()
    cy.get('button').contains('7').click()
    cy.get('button').contains('9').click()
    cy.get('button').contains('=').click()
    cy.get('[data-cy=display-value]').contains('89376.702')
  })

it('divide operation',  () => {
    cy.get('button').contains('C').click()

    cy.get('button').contains('2').click()
    cy.get('button').contains('/').click()
    cy.get('button').contains('2').click()
    cy.get('button').contains('=').click()
    cy.get('[data-cy=display-value]').contains('1')

    cy.get('button').contains('C').click()

    cy.get('button').contains('2').click()
    cy.get('button').contains('2').click()
    cy.get('button').contains('/').click()
    cy.get('button').contains('0').click()
    cy.get('button').contains('=').click()
    cy.get('[data-cy=display-value]').contains('Error')

    cy.get('button').contains('C').click()

    cy.get('button').contains('0').click()
    cy.get('button').contains('/').click()
    cy.get('button').contains('8').click()
    cy.get('button').contains('=').click()
    cy.get('[data-cy=display-value]').contains('0')

    cy.get('button').contains('C').click()

    cy.get('button').contains('1').click()
    cy.get('button').contains('2').click()
    cy.get('button').contains('3').click()
    cy.get('button').contains('/').click()
    cy.get('button').contains('0').click()
    cy.get('button').contains('.').click()
    cy.get('button').contains('3').click()
    cy.get('button').contains('=').click()
    cy.get('[data-cy=display-value]').contains('410')

    cy.get('button').contains('C').click()

    cy.get('button').contains('7').click()
    cy.get('button').contains('2').click()
    cy.get('button').contains('9').click()
    cy.get('button').contains('5').click()
    cy.get('button').contains('.').click()
    cy.get('button').contains('2').click()
    cy.get('button').contains('0').click()
    cy.get('button').contains('6').click()
    cy.get('button').contains('4').click()
    cy.get('button').contains('/').click()
    cy.get('button').contains('3').click()
    cy.get('button').contains('6').click()
    cy.get('button').contains('6').click()
    cy.get('button').contains('.').click()
    cy.get('button').contains('8').click()
    cy.get('button').contains('=').click()
    cy.get('[data-cy=display-value]').contains('19.889')
  })

it('divide with remainder operation (%)',  () => {
  cy.get('button').contains('C').click()

  cy.get('button').contains('7').click()
  cy.get('button').contains('%').click()
  cy.get('button').contains('5').click()
  cy.get('button').contains('=').click()
  cy.get('[data-cy=display-value]').contains('2')

  cy.get('button').contains('C').click()

  cy.get('button').contains('2').click()
  cy.get('button').contains('2').click()
  cy.get('button').contains('%').click()
  cy.get('button').contains('0').click()
  cy.get('button').contains('=').click()
  cy.get('[data-cy=display-value]').contains('Error')

  cy.get('button').contains('C').click()

  cy.get('button').contains('0').click()
  cy.get('button').contains('%').click()
  cy.get('button').contains('2').click()
  cy.get('button').contains('=').click()
  cy.get('[data-cy=display-value]').contains('0')

  cy.get('button').contains('C').click()

  cy.get('button').contains('1').click()
  cy.get('button').contains('2').click()
  cy.get('button').contains('3').click()
  cy.get('button').contains('%').click()
  cy.get('button').contains('0').click()
  cy.get('button').contains('.').click()
  cy.get('button').contains('3').click()
  cy.get('button').contains('=').click()
  cy.get('[data-cy=display-value]').contains('Error')

  cy.get('button').contains('C').click()

  cy.get('button').contains('7').click()
  cy.get('button').contains('2').click()
  cy.get('button').contains('9').click()
  cy.get('button').contains('%').click()
  cy.get('button').contains('3').click()
  cy.get('button').contains('6').click()
  cy.get('button').contains('=').click()
  cy.get('[data-cy=display-value]').contains('9')
})

it('operation with brackets',  () => {
  cy.get('button').contains('C').click()

  cy.get('button').contains('(').click()
  cy.get('button').contains('5').click()
  cy.get('button').contains('+').click()
  cy.get('button').contains('3').click()
  cy.get('button').contains(')').click()
  cy.get('button').contains('*').click()
  cy.get('button').contains('(').click()
  cy.get('button').contains('0').click()
  cy.get('button').contains('-').click()
  cy.get('button').contains('3').click()
  cy.get('button').contains(')').click()
  cy.get('button').contains('=').click()
  cy.get('[data-cy=display-value]').contains('-24')

  cy.get('button').contains('C').click()

  cy.get('button').contains('5').click()
  cy.get('button').contains('-').click()
  cy.get('button').contains('(').click()
  cy.get('button').contains('3').click()
  cy.get('button').contains('+').click()
  cy.get('button').contains('(').click()
  cy.get('button').contains('6').click()
  cy.get('button').contains('6').click()
  cy.get('button').contains('-').click()
  cy.get('button').contains('3').click()
  cy.get('button').contains(')').click()
  cy.get('button').contains('+').click()
  cy.get('button').contains('8').click()
  cy.get('button').contains('7').click()
  cy.get('button').contains(')').click()
  cy.get('button').contains('=').click()
  cy.get('[data-cy=display-value]').contains('-148')

  cy.get('button').contains('C').click()

  cy.get('button').contains('1').click()
  cy.get('button').contains('4').click()
  cy.get('button').contains('*').click()
  cy.get('button').contains('8').click()
  cy.get('button').contains('/').click()
  cy.get('button').contains('(').click()
  cy.get('button').contains('3').click()
  cy.get('button').contains('-').click()
  cy.get('button').contains('1').click()
  cy.get('button').contains('7').click()
  cy.get('button').contains('*').click()
  cy.get('button').contains('(').click()
  cy.get('button').contains('9').click()
  cy.get('button').contains('1').click()
  cy.get('button').contains('+').click()
  cy.get('button').contains('4').click()
  cy.get('button').contains('*').click()
  cy.get('button').contains('8').click()
  cy.get('button').contains('-').click()
  cy.get('button').contains('(').click()
  cy.get('button').contains('4').click()
  cy.get('button').contains('+').click()
  cy.get('button').contains('2').click()
  cy.get('button').contains(')').click()
  cy.get('button').contains(')').click()
  cy.get('button').contains(')').click()
  cy.get('button').contains('=').click()
  cy.get('[data-cy=display-value]').contains('-0.056')
})

})
